### PR TITLE
Fixed a small typo

### PR DESCRIPTION
**Pull request by UdeshyaDhungana**

### CODE REVIEW

**Comment by iamcco** [comment]
Thanks!

**Comment by UdeshyaDhungana** [comment]
My pleasure! But the checks have failed! 😅  What went wrong? (I'm just learning pull requests, so I did not understand)

**Comment by iamcco** [comment]
It's not relative to this.

**Comment by UdeshyaDhungana** [comment]
Oh, alright. Thanks!

**Pull request merged**
